name: Clean release
run-name: ${{ github.actor }} release
on:
  push:
    tags:
    - '*'
jobs:
  pypi-release:
    runs-on: ubuntu-latest
    container:
      image: yourlabs/python
    steps:
    - name: Check out repository code
      uses: actions/checkout@v3
    - name: debug this crazy environment
      run: |
        set -x
        npm install
        chown -R root:root .
        npm run compile-js
        chown -R root:root .
        npm run minify-js
        chown -R root:root .
        cp node_modules/select2/dist/css/*.css src/dal_select2/static/vendor/select2/dist/css/*.css
        ls -lah node_modules/select2/dist/css/*.css src/dal_select2/static/vendor/select2/dist/css/*.css
        lsattr node_modules/select2/dist/css/*.css src/dal_select2/static/vendor/select2/dist/css/*.css
    - name: Update version in setup.py and docs/conf.py
      run: |
        sed -i "s/version=[^,]*,/version='${GITHUB_REF##*/}',/" setup.py
        sed -i "s/release = [^,]*,/release = '${GITHUB_REF##*/}'/" docs/conf.py
        sed -i 's/version": "[^"]*"/version": "$short"/' package.json
        short=$(echo ${GITHUB_REF##*/} | grep -Eo '[^.]+\.[^.]+')
        sed -i "s/version = [^,]*,/version = '${GITHUB_REF##*/}'/" docs/conf.py
    - name: Update changelog
      run: echo -e "$(python changelog.py ${GITHUB_REF##*/})\n$(cat CHANGELOG)" > CHANGELOG
    - uses: stefanzweifel/git-auto-commit-action@v4
    - name: Build python package
      run: python setup.py sdist
