name: Clean release
run-name: ${{ github.actor }} release
on: push
jobs:
  pypi-release:
    runs-on: ubuntu-latest
    container:
      image: yourlabs/python
    steps:
    - name: Check out repository code
      uses: actions/checkout@v3
    - name: debug this crazy environment
      run: |
        set -x
        npm install
        npm run build
    - name: Update version in setup.py and docs/conf.py
      run: |
        sed -i "s/version=[^,]*,/version='${GITHUB_REF##*/}',/" setup.py
        sed -i "s/release = [^,]*,/release = '${GITHUB_REF##*/}'/" docs/conf.py
        sed -i 's/version": "[^"]*"/version": "$short"/' package.json
        short=$(echo ${GITHUB_REF##*/} | grep -Eo '[^.]+\.[^.]+')
        sed -i "s/version = [^,]*,/version = '${GITHUB_REF##*/}'/" docs/conf.py
    - name: Update changelog
      run: echo -e "$(python changelog.py ${GITHUB_REF##*/})\n$(cat CHANGELOG)" > CHANGELOG
    - uses: stefanzweifel/git-auto-commit-action@v4
    - name: Build python package
      run: python setup.py sdist
